apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/metrics-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

