apiVersion: v1
kind: Pod
metadata:
  name: mypvcpod
spec:
  containers:
    - name: myfrontend
      image: nginx
      envFrom:
      - configMapRef:
          name: myenvconfig
      volumeMounts:
      - name: mypd
        mountPath: "/var/www/html"
      - name: config-volume
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3

  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: task-pv-claim
    - name: config-volume
      configMap: 
        name: nginx-config
  initContainers:
    - name: wait-before-start
      image: busybox
      command: ["sh", "-c", "echo 'Simulating delay'; sleep 30"]

